spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mail:
    host: SMTP.qq.com
    port: 465
    username: 1744969381@qq.com
    password: vclvankureuzcjcf
    protocol: smtps
  redis:
    # Redis数据库索引（默认为0）
    database: 11
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
    listener:
      missing-topics-fatal: false

mybatis:
  #这里是实体类所在的包
  type-aliases-package: com.lsy.community.entity
  #这里是放sql语句的映射文件
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true
    # 可将自动生成的主键id返回(eg:我们可在user刚执行完插入保证后下一步直接user.getId()获取id值)
    useGeneratedKeys: true

server:
  port: 4025
  servlet:
    context-path: /community

community:
  path:
    domain: http://localhost:4025
    upload: d:/work/data/upload
