spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  #这里是实体类所在的包
  type-aliases-package: com.lsy.community.entity
  #这里是放sql语句的映射文件
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  level:
#    root: info
#  file:
#    path: D:/log/data/community.log

server:
  port: 4025
